apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: nexoryx-ai
spec:
  serviceName: qdrant
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant
        ports:
        - containerPort: 6333
        volumeMounts:
        - mountPath: /qdrant/storage
          name: qdrant-storage
  volumeClaimTemplates:
  - metadata:
      name: qdrant-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: nexoryx-ai
spec:
  selector:
    app: qdrant
  ports:
  - port: 6333
    targetPort: 6333
